/* eslint import/prefer-default-export: 0 */
export const productActions = {
  PRODUCTS_IS_LOADING: 'PRODUCTS_IS_LOADING',
  PRODUCTS_ERROR: 'PRODUCTS_ERROR',
  PRODUCTS_RESET: 'PRODUCTS_RESET',
  PRODUCTS_NEW: 'PRODUCTS_NEW',
  PRODUCTS: 'PRODUCTS',
  SELECT_PRODUCT: 'SELECT_PRODUCT',
  PRODUCT_SUCCESS: 'PRODUCT_SUCCESS',
  SELECT_PRODUCT_RESET: 'SELECT_PRODUCT_RESET',
  PRODUCT_POSTCREATE: 'PRODUCT_POSTCREATE'
};

export const userActions = {
  USERS_IS_LOADING: 'USERS_IS_LOADING',
  USERS_ERROR: 'USERS_ERROR',
  USERS_RESET: 'USERS_RESET',
  USERS_NEW: 'USERS_NEW',
  USERS: 'USERS'
};

export const reservationActions = {
  RESERVATIONS_IS_LOADING: 'RESERVATIONS_IS_LOADING',
  RESERVATIONS_ERROR: 'RESERVATIONS_ERROR',
  RESERVATIONS_RESET: 'RESERVATIONS_RESET',
  RESERVATIONS_NEW: 'RESERVATIONS_NEW',
  RESERVATIONS: 'RESERVATIONS'
};